version: '3.6'
services:

  mailserver:
    networks: 
      - net_mailserver
    build:
      network: host
      context: ./MailServer
      dockerfile: ./Dockerfile
    ports:
      - "5700:80"

networks:
  net_mailserver:
    name: net_mailserver
