# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DFMailServerCI

inputs:
  NUGET_TOKEN:
    description: 'Nuget pwd'
    required: true

runs:
    using: "composite"
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Build client
    - name: Update GitHub nuget repository
      run: dotnet nuget update source github --store-password-in-clear-text --configfile "MailClient/NuGet.config" --username ${{ vars.NUGET_USERNAME }} --password ${{ inputs.NUGET_TOKEN }}
    - name: MailClient - Restore dependencies
      run: dotnet restore MailClient/MailClient.csproj
    - name: MailClient - Build
      run: dotnet build --no-restore MailClient/MailClient.csproj --configuration Release

#    - name: Test
#      run: dotnet test --no-build --verbosity normal
