# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Client NuGet package

on:
  workflow_dispatch:
 
jobs:
  build:
    uses: ./.github/workflows/build_client.yml
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  
  # Deploy step
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Update GitHub nuget repository
      run: 
        dotnet nuget add --source github --store-password-in-clear-text  --username ${{ vars.NUGET_USERNAME }} --password ${{ secrets.NUGET_TOKEN }}
    - name: MailClient - Deploy package
      run: 
        dotnet nuget push "MailClient/bin/Release/*.nupkg"  --api-key ${{ secrets.NUGET_TOKEN }} --source "github" --skip-duplicate
  