# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MailClient - Deploy NuGet package

on:

  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/mailclient_deploy.yml'
    
jobs:
  build:
    uses: ./.github/workflows/mailclient_ci.yml
    secrets:
      NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  
  # Deploy step
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Config
      run: dotnet nuget add source "DarkFactorAS" --store-password-in-clear-text --configfile "MailClient/NuGet.config" --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_TOKEN }}

    - name: MailClient - Deploy package
      run: 
        dotnet nuget push "MailClient/bin/Release/*.nupkg"  --api-key ${{ secrets.NUGET_TOKEN }} --source "DarkFactorAS" --skip-duplicate
  